parts_map = {
    'Hips': 0,
    'RightUpLeg': 2,
    'RightLeg': 5,
    'RightFoot': 8,
    'RightToeBase': 11,
    'LeftUpLeg': 1,
    'LeftLeg': 4,
    'LeftFoot': 7,
    'LeftToeBase': 10,
    'Spine': 3,
    'Spine1': 6,
    'Spine2': 9,
    'LeftShoulder': 13,
    'LeftArm': 16,
    'LeftForeArm': 18,
    'SMPL_LeftWrist': 20,
    'SMPL_LeftHand': 22,
    'RightShoulder': 14,
    'RightArm': 17,
    'RightForeArm': 19,
    'SMPL_RightWrist': 21,
    'SMPL_RightHand': 23,
    'Neck': 12,
    'Head': 15,
    'SMPLH_left_middle1': 25,
    'SMPLH_right_middle1': 40
}
